package com.sjmeunier.arborfamiliae.reports;

import android.content.Context;

import com.sjmeunier.arborfamiliae.util.AncestryUtil;
import com.sjmeunier.arborfamiliae.data.NameFormat;
import com.sjmeunier.arborfamiliae.database.AppDatabase;
import com.sjmeunier.arborfamiliae.database.Family;
import com.sjmeunier.arborfamiliae.database.FamilyChild;
import com.sjmeunier.arborfamiliae.database.Individual;
import com.sjmeunier.arborfamiliae.database.Place;
import com.sjmeunier.arborfamiliae.util.ListSearchUtils;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.Map;

public class DescendantReport extends BaseReport {

    public DescendantReport(Context context, AppDatabase database, Map<Integer, Place> placesInActiveTree, Map<Integer, Individual> individualsInActiveTree, Map<Integer, Family> familiesInActiveTree, List<FamilyChild> familyChildrenInActiveTree, NameFormat nameFormat, int maxGenerations, int treeId) {
        super(context, database, placesInActiveTree, individualsInActiveTree, familiesInActiveTree, familyChildrenInActiveTree, nameFormat, maxGenerations, treeId);
    }

    @Override
    public boolean generateReport(String filename, int activeIndividualId) throws IOException {
        this.configureOutputFile(filename);
        if (this.individualsInActiveTree.containsKey(activeIndividualId)) {
            Individual individual = this.individualsInActiveTree.get(activeIndividualId);
            String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
            this.writeLine("Descendant report of " + AncestryUtil.generateName(individual, this.nameFormat));
            this.writeLine("Generated by Arbor Familiae at " + timeStamp);
            this.writeLine("");
            this.writeLine("");
        }
        processPerson(activeIndividualId, 1);
        closeFile();
        return true;
    }

    private void processPerson(int individualId, int generation) throws IOException  {
        if (!this.individualsInActiveTree.containsKey(individualId))
            return;

        Individual individual = this.individualsInActiveTree.get(individualId);
        this.writeLine(new String(new char[generation * 2]).replace('\0', ' ') + "- " + AncestryUtil.generateName(individual, this.nameFormat) + " " + AncestryUtil.generateBirthDeathDateWithPlace(individual, this.placesInActiveTree));

        List<Family> families = ListSearchUtils.findFamiliesForWifeOrHusband(individualId, this.familiesInActiveTree);
        for(Family family : families) {
            //Spouse
            if (family.wifeId == individualId) {
                if (family.husbandId == -1 || !this.individualsInActiveTree.containsKey(family.husbandId)) {
                    this.writeLine(new String(new char[generation * 2]).replace('\0', ' ') + "  x <Unknown>");
                } else {
                    this.writeLine(new String(new char[generation * 2]).replace('\0', ' ') + "  " + AncestryUtil.getMarriageLine(this.individualsInActiveTree.get(family.husbandId), family, nameFormat, this.placesInActiveTree, false));
                }
            } else {
                if (family.wifeId == -1 || !this.individualsInActiveTree.containsKey(family.wifeId)) {
                    this.writeLine(new String(new char[generation * 2]).replace('\0', ' ') + "  x <Unknown>");
                } else {
                    this.writeLine(new String(new char[generation * 2]).replace('\0', ' ') + "  " + AncestryUtil.getMarriageLine(this.individualsInActiveTree.get(family.wifeId), family, nameFormat, this.placesInActiveTree, false));
                }
            }

            //Children
            if (generation < this.maxGenerations) {
                List<FamilyChild> familyChildren = ListSearchUtils.findChildrenForFamily(family.familyId, this.familyChildrenInActiveTree);
                for(FamilyChild familyChild : familyChildren) {
                    processPerson(familyChild.individualId, generation + 1);
                }
            }
        }
    }
}
