package com.sjmeunier.arborfamiliae.reports;

import android.content.Context;

import com.sjmeunier.arborfamiliae.database.FamilyChild;
import com.sjmeunier.arborfamiliae.util.AncestryUtil;
import com.sjmeunier.arborfamiliae.data.NameFormat;
import com.sjmeunier.arborfamiliae.database.AppDatabase;
import com.sjmeunier.arborfamiliae.database.Family;
import com.sjmeunier.arborfamiliae.database.Individual;
import com.sjmeunier.arborfamiliae.database.Place;
import com.sjmeunier.arborfamiliae.util.ListSearchUtils;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PlacesReport extends BaseReport {

    private Map<String, Integer> placesWithCount;
    private List<String> places;
    private List<Integer> ancestorIds;
    private IncludedIndividuals includedIndividuals;

    public PlacesReport(Context context, Map<Integer, Place> placesInActiveTree, Map<Integer, Individual> individualsInActiveTree, Map<Integer, Family> familiesInActiveTree, List<FamilyChild> familyChildrenInActiveTree, NameFormat nameFormat, IncludedIndividuals includedIndividuals, int maxGenerations, int treeId) {
        super(context, placesInActiveTree, individualsInActiveTree, familiesInActiveTree, familyChildrenInActiveTree, nameFormat, maxGenerations, treeId);
        this.includedIndividuals = includedIndividuals;
    }

    @Override
    public boolean generateReport(String filename, int activeIndividualId) throws IOException {
        this.configureOutputFile(filename);
        ancestorIds = new ArrayList<>();
        placesWithCount = new HashMap<>();
        places = new ArrayList<>();

        if (this.individualsInActiveTree.containsKey(activeIndividualId)) {
            Individual individual = this.individualsInActiveTree.get(activeIndividualId);
            String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
            if (includedIndividuals == IncludedIndividuals.Ancestors)
                this.writeLine("Places report for the ancestors of " + AncestryUtil.generateName(individual, this.nameFormat));
            else if (includedIndividuals == IncludedIndividuals.Decendants)
                this.writeLine("Places report for the descendants of " + AncestryUtil.generateName(individual, this.nameFormat));
            else
                this.writeLine("Places report for all individuals in the tree");
            this.writeLine("Generated by Arbor Familiae at " + timeStamp);
            this.writeLine("");
            this.writeLine("");
        }

        if (includedIndividuals == IncludedIndividuals.Ancestors)
            this.processAncestorsIndividual(activeIndividualId, 1);
        else if (includedIndividuals == IncludedIndividuals.Decendants)
            this.processDescendantsIndividual(activeIndividualId, 1);
        else
            this.processAllIndividuals();

        this.outputReport();
        this.closeFile();

        return true;
    }

    private void outputReport() throws IOException {
        Collections.sort(places);
        for(String place : places) {
            this.writeLine(place + " (" + String.valueOf(placesWithCount.get(place)) + ")");
        }
    }

    private void getPlacesFromIndividual(Individual individual) {
        if (individual.birthPlace != -1 && this.placesInActiveTree.get(individual.birthPlace) != null) {
            Place place = this.placesInActiveTree.get(individual.birthPlace);
            if (placesWithCount.containsKey(place.placeName)) {
                placesWithCount.put(place.placeName, placesWithCount.get(place.placeName) + 1);
            } else {
                placesWithCount.put(place.placeName, 1);
                places.add(place.placeName);
            }
        }
        if (individual.baptismPlace != -1 && this.placesInActiveTree.get(individual.baptismPlace) != null) {
            Place place = this.placesInActiveTree.get(individual.baptismPlace);
            if (placesWithCount.containsKey(place.placeName)) {
                placesWithCount.put(place.placeName, placesWithCount.get(place.placeName) + 1);
            } else {
                placesWithCount.put(place.placeName, 1);
                places.add(place.placeName);
            }
        }

        if (individual.diedPlace != -1 && this.placesInActiveTree.get(individual.diedPlace) != null) {
            Place place = this.placesInActiveTree.get(individual.diedPlace);
            if (placesWithCount.containsKey(place.placeName)) {
                placesWithCount.put(place.placeName, placesWithCount.get(place.placeName) + 1);
            } else {
                placesWithCount.put(place.placeName, 1);
                places.add(place.placeName);
            }
        }

        if (individual.burialPlace != -1 && this.placesInActiveTree.get(individual.burialPlace) != null) {
            Place place = this.placesInActiveTree.get(individual.burialPlace);
            if (placesWithCount.containsKey(place.placeName)) {
                placesWithCount.put(place.placeName, placesWithCount.get(place.placeName) + 1);
            } else {
                placesWithCount.put(place.placeName, 1);
                places.add(place.placeName);
            }
        }
    }

    private void getPlacesFromFamily(Family family) {
        if (family.marriagePlace != -1 && this.placesInActiveTree.get(family.marriagePlace) != null) {
            Place place = this.placesInActiveTree.get(family.marriagePlace);
            if (placesWithCount.containsKey(place.placeName)) {
                placesWithCount.put(place.placeName, placesWithCount.get(place.placeName) + 1);
            } else {
                placesWithCount.put(place.placeName, 1);
                places.add(place.placeName);
            }
        }
    }

    private void processAncestorsIndividual(int individualId, int generation) {
        if (!this.individualsInActiveTree.containsKey(individualId))
            return;

        if (!ancestorIds.contains(individualId) && this.individualsInActiveTree.containsKey(individualId)) {
            ancestorIds.add(individualId);
            Individual individual = this.individualsInActiveTree.get(individualId);
            getPlacesFromIndividual(individual);

            List<Family> families = ListSearchUtils.findFamiliesForWifeOrHusband(individualId, familiesInActiveTree);
            for(Family family : families) {
                getPlacesFromFamily(family);
            }

            if (generation < this.maxGenerations) {
                if (individual.parentFamilyId != -1 && this.familiesInActiveTree.containsKey(individual.parentFamilyId)) {
                    Family family = this.familiesInActiveTree.get(individual.parentFamilyId);
                    if (family.husbandId != -1) {
                        processAncestorsIndividual(family.husbandId, generation + 1);
                    }
                    if (family.wifeId != -1) {
                        processAncestorsIndividual(family.wifeId, generation + 1);
                    }
                }
            }
        } else {
            return;
        }

    }

    private void processDescendantsIndividual(int individualId, int generation) {
        if (!this.individualsInActiveTree.containsKey(individualId))
            return;

        if (!ancestorIds.contains(individualId) && this.individualsInActiveTree.containsKey(individualId)) {
            ancestorIds.add(individualId);
            Individual individual = this.individualsInActiveTree.get(individualId);
            getPlacesFromIndividual(individual);

            List<Family> families = ListSearchUtils.findFamiliesForWifeOrHusband(individualId, familiesInActiveTree);
            for(Family family : families) {
                getPlacesFromFamily(family);

                if (generation < this.maxGenerations) {
                    List<FamilyChild> familyChildren = ListSearchUtils.findChildrenForFamily(family.familyId, this.familyChildrenInActiveTree);
                    for(FamilyChild familyChild : familyChildren) {
                        if (this.individualsInActiveTree.containsKey(familyChild.individualId)) {
                            processDescendantsIndividual(familyChild.individualId, generation + 1);
                        }
                    }
                }
            }

        } else {
            return;
        }
    }


    private void processAllIndividuals() {
        for(Individual individual : this.individualsInActiveTree.values()) {
            getPlacesFromIndividual(individual);

            List<Family> families = ListSearchUtils.findFamiliesForWifeOrHusband(individual.individualId, familiesInActiveTree);
            for(Family family : families) {
                getPlacesFromFamily(family);
            }
        }
    }
}
